/**
 * Převod českých křestních jmen do 5. pádu (vokativu).
 * Pokrývá ~220 nejčastějších českých jmen + pravidlová fallback logika.
 * Cizí/neznámá jména se vrací v 1. pádu (beze změny).
 */

// Explicitní mapa: jméno v 1. pádu → 5. pád
// Obsahuje běžná česká mužská i ženská jména včetně výjimek
const VOCATIVE_MAP: Record<string, string> = {
  // Mužská jména
  Adam: 'Adame',
  Aleš: 'Aleši',
  Alexandr: 'Alexandre',
  Alois: 'Aloisi',
  Antonín: 'Antoníne',
  Arnošt: 'Arnošte',
  Bedřich: 'Bedřichu',
  Bohumil: 'Bohumile',
  Bohumír: 'Bohumíre',
  Bohuslav: 'Bohuslave',
  Boris: 'Borisi',
  Břetislav: 'Břetislave',
  Čeněk: 'Čeňku',
  Dalibor: 'Dalibore',
  Daniel: 'Danieli',
  David: 'Davide',
  Denis: 'Denisi',
  Dominik: 'Dominiku',
  Dušan: 'Dušane',
  Eduard: 'Eduarde',
  Emil: 'Emile',
  Erik: 'Eriku',
  Filip: 'Filipe',
  František: 'Františku',
  Hynek: 'Hynku',
  Igor: 'Igore',
  Ivan: 'Ivane',
  Ivo: 'Ivo',
  Jakub: 'Jakube',
  Jan: 'Jane',
  Jaromír: 'Jaromíre',
  Jaroslav: 'Jaroslave',
  Jindřich: 'Jindřichu',
  Jiří: 'Jiří',
  Josef: 'Josefe',
  Kamil: 'Kamile',
  Karel: 'Karle',
  Kryštof: 'Kryštofe',
  Ladislav: 'Ladislave',
  Leoš: 'Leoši',
  Libor: 'Libore',
  Lubomír: 'Lubomíre',
  Luboš: 'Luboši',
  Ludvík: 'Ludvíku',
  Lukáš: 'Lukáši',
  Marcel: 'Marceli',
  Marek: 'Marku',
  Martin: 'Martine',
  Matěj: 'Matěji',
  Matyáš: 'Matyáši',
  Michael: 'Michaeli',
  Michal: 'Michale',
  Milan: 'Milane',
  Miloslav: 'Miloslave',
  Miloš: 'Miloši',
  Miroslav: 'Miroslave',
  Mojmír: 'Mojmíre',
  Oldřich: 'Oldřichu',
  Ondřej: 'Ondřeji',
  Otakar: 'Otakare',
  Patrik: 'Patriku',
  Pavel: 'Pavle',
  Petr: 'Petře',
  Přemysl: 'Přemysle',
  Radek: 'Radku',
  Radim: 'Radime',
  Radomír: 'Radomíre',
  René: 'René',
  Richard: 'Richarde',
  Robert: 'Roberte',
  Robin: 'Robine',
  Roman: 'Romane',
  Rostislav: 'Rostislave',
  Rudolf: 'Rudolfe',
  Samuel: 'Samueli',
  Sebastian: 'Sebastiane',
  Stanislav: 'Stanislave',
  Šimon: 'Šimone',
  Štěpán: 'Štěpáne',
  Štefan: 'Štefane',
  Theodor: 'Theodore',
  Tobiáš: 'Tobiáši',
  Tomáš: 'Tomáši',
  Václav: 'Václave',
  Viktor: 'Viktore',
  Vilém: 'Viléme',
  Vít: 'Víte',
  Vladimír: 'Vladimíre',
  Vladislav: 'Vladislave',
  Vlastimil: 'Vlastimile',
  Vojtěch: 'Vojtěchu',
  Vratislav: 'Vratislave',
  Zbyněk: 'Zbyňku',
  Zdeněk: 'Zdeňku',

  // Ženská jména (většina -o nebo -ko koncovka)
  Adéla: 'Adélo',
  Alena: 'Aleno',
  Alice: 'Alice',
  Alžběta: 'Alžběto',
  Andrea: 'Andreo',
  Aneta: 'Aneto',
  Anežka: 'Anežko',
  Anna: 'Anno',
  Barbora: 'Barboro',
  Blanka: 'Blanko',
  Božena: 'Boženo',
  Dana: 'Dano',
  Daniela: 'Danielo',
  Denisa: 'Deniso',
  Dominika: 'Dominiko',
  Eliška: 'Eliško',
  Ema: 'Emo',
  Eva: 'Evo',
  Gabriela: 'Gabrielo',
  Hana: 'Hano',
  Helena: 'Heleno',
  Iva: 'Ivo',
  Ivana: 'Ivano',
  Iveta: 'Iveto',
  Jana: 'Jano',
  Jarmila: 'Jarmilo',
  Jaroslava: 'Jaroslavo',
  Jiřina: 'Jiřino',
  Jitka: 'Jitko',
  Kamila: 'Kamilo',
  Karolína: 'Karolíno',
  Kateřina: 'Kateřino',
  Klára: 'Kláro',
  Kristýna: 'Kristýno',
  Květa: 'Květo',
  Lenka: 'Lenko',
  Libuše: 'Libuše',
  Lucie: 'Lucie',
  Ludmila: 'Ludmilo',
  Marcela: 'Marcelo',
  Marie: 'Marie',
  Markéta: 'Markéto',
  Marta: 'Marto',
  Martina: 'Martino',
  Michaela: 'Michaelo',
  Milena: 'Mileno',
  Miroslava: 'Miroslavo',
  Monika: 'Moniko',
  Natalka: 'Natalko',
  Natálie: 'Natálie',
  Nikola: 'Nikolo',
  Nina: 'Nino',
  Olga: 'Olgo',
  Pavla: 'Pavlo',
  Pavlína: 'Pavlíno',
  Petra: 'Petro',
  Radka: 'Radko',
  Renáta: 'Renáto',
  Romana: 'Romano',
  Růžena: 'Růženo',
  Simona: 'Simono',
  Soňa: 'Soňo',
  Šárka: 'Šárko',
  Šarlota: 'Šarloto',
  Štěpánka: 'Štěpánko',
  Tereza: 'Terezo',
  Veronika: 'Veroniko',
  Věra: 'Věro',
  Viktorie: 'Viktorie',
  Vlasta: 'Vlasto',
  Zdenka: 'Zdenko',
  Zdeňka: 'Zdeňko',
  Zuzana: 'Zuzano',
};

/**
 * Převede křestní jméno do 5. pádu (vokativu).
 * Neznámá/cizí jména vrací beze změny.
 */
export function toVocative(name: string): string {
  if (!name || name.trim().length === 0) return name;

  const trimmed = name.trim();

  // Zkusíme přesnou shodu v mapě (case-sensitive)
  if (VOCATIVE_MAP[trimmed]) {
    return VOCATIVE_MAP[trimmed];
  }

  // Zkusíme shodu s prvním písmenem velkým
  const capitalized = trimmed.charAt(0).toUpperCase() + trimmed.slice(1).toLowerCase();
  if (VOCATIVE_MAP[capitalized]) {
    return VOCATIVE_MAP[capitalized];
  }

  // Neznámé jméno — vrátíme beze změny (bezpečnější než špatný tvar)
  return trimmed;
}
